language: node_js
servers: mongodb
node_js:
- node
- '12'
install:
- cd backend ; npm install
- cd backend ; npm install -dev
script:
- cd backend ; npm test
notifications:
  slack: nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt
env:
  global:
  - secure: cjjRhA6HA6Oe1MgXlI7WsLZzh9XuLCL7R2/dZPRm07C81NpQhuFrQ/VUgisdrmi5lmQnh7MRVb+AZ1K5Em5s8pIIuLeW5bGq4kc/73QBruMBqxEWjkQfl5qbHXDpaTJZnX5v7vj+x67xM69HXnSTL1UiV6W/MUZ/Yu59+4jYZzGeuP197AA8kmX8KQ2J3K/bAP18TDsgm87aciy3SShxAx8lH5FmHPf2fO4DrLAue+a8Pvu8V8VFEtZ/afymH1zOvwEBzvQPdUOfdh6p82OKNUqfORATPaXEjoYrZEqR4NqIWfvFUmQZW5zJz2NeKMW6GFwVST33KrIr0+PxS6s59FPl2nd/80/DeYRIwzY2exQBWzoXnlD63cX4N7KXfRiJzlVmXahni74lmvYgJCfmxm25U1XQoqyEixaM8ScHdJnro1jeT/qRk+742MxsnFQJOnlUS2xuicRb65yXETBeH8HswVUsZqIz7JfBbBcfytne0xu18uVISsMvFdGRaT1wf2TUgyhEk8b1XAHpEhzc3DWRx2RPcoW9YMVK1KjLnNSRPL438QAb748GT96s+3PVqmMShborrCMOWxd5rWldat0PU1nOwsmftSp6JnSINGUgAhDPdWppWwh1lsCp2Ck7AXmkTf31SDjKUgb3eZhc/snZE1cWP6m3lUibyu3PO8g=
  - secure: MlBjxcifubsmGg2jK0UaYD2yqrv6UnKNZ0rF9113116vXhcgrJYxB1qwPUy9WTwHqPxnawR/jBJ2PN+Biy8txR3PJOVGF8hWFp11/J9LMGpERVa79NkNYgf7kr4hHRCtsPkxTImGkdyfQVM5rtTdU6Av82q4Il8c2BVs4DnumOze6dRiXJJnCaqods+4guiHP8IUyG4GgJzd3AnA0iv7b7fHtyiQfxbpinf7c/KrL6FWsLpxa3QkPi5N9Sy4bTOVbw+ZuwR6wMqp0Z6tfgKIxc7iAAmtk7LYK4rPai/TtUwkvDaiwiRo/oRHvsjUBL4zsBgi4aLukJkB9MkKEXIIIgfEiVTlA0xcTrkYoLJBuikSppI3xrSQt1c4MvvDgLhWIT3WaKigQPOvGbx9pvujTAL52s9YpoGGXnsTS8XcOW2zhLB4xorNuQi9eFsAfSLQjuLuA4A/gMNQDqeYbfRbg/urpyEWYFxkAFbGAnL9sHrNFgJSMRrr6Hg5xFUq0Bt7MryxlIvBJlVifZypWyWXCD1ln6yNxnuXYubi2l6OJuYRMpGm8xmbfxP8HzAkb+SQ80MSbzllPGGnkun1++nobqNyCijk4hGFryujCxhRIqzoL8jxAzetGC6s71tC5gHCf/47z+q9PuBEMH91l6LVmovFjFiAUH+k5pSZHscQISw=
