language: node_js
node_js:
  - "node"
  - "12"
install:
  - cd backend ; npm install
  - cd backend ; npm install -dev
script:
  - cd backend ; npm test
notifications:
  slack: nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt