language: node_js
servers: mongodb
node_js:
- node
- '12'
install:
- cd backend ; npm install
- cd backend ; npm install -dev
script:
- cd backend ; npm test
notifications:
  slack: nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt
env:
  global:
  - secure: bhyX2NzsmyQcwdl8ZkDZwvugQt86O/HTWG+ojV3wApaYWBiCtjfybeVqLgnbPTxTuj1pCX9ySFGwiQh9BW+3WGpvFaIevUk33NXSUznO7aMWZLcJs8GCvPYYGGJb4taxQ9WHoFS7X9r/QQniS1e8dva/62G04Ck2Z1lj0UXtxOfknXaGqDrR05vUDkXV0qEuaG0El6pg9/RD5cUR+gUItzD7HX5RX727ulA/wbnYtDjUKtsfSEzv54VyCFBIyOSt4e5/tf/Oeo5QY/7R5EdAE2ZYce2Aojt3bUy3JG19Rv8Q0E15k3nR+BPF5KRc0HzEUvlTriXz9gLFJALywQuQUIyzkTfZNJmOz3vJFY7hMX18vmJ9En0zoAiLvpxEQZ8+eDr1ZNpAG5zkMVLdnTFhSLtqbCrAFzLCevR3hGkccsZinJxdKx9BLni7/qnxiXAC9JNIRU1rSctHQYT6zF2DP9+TJ4hI9BAKii2512XzjTKMoraPy262C+WC0uyXW9iozmiHSkPCSzXTdEFBoHxq/W4+jfZYEzRRdmBWzQ1cK/UFsl/CXwOOlY9gtEr14hPEPuUSyfnz7AYucZEGkkcrlazlkzNpNfpCxfZqokIhOEVC+nPB5Ger1FE2Vbv1tQ28PV02K+pwaU67L566rHyvPvyjj45GiOSELB6g3XOzefE=
  - secure: R6fkGe7U2lDeKwScqEeVa8aipG/E+zmZPfwdAtJ9kkixNEujthmBcGqnMBg/oQjaEuRC7+8c8Zx41J3zEiDht6nj+MsUbbCEj1kJeg4dTQCZLyCu8eQ34uANOYrcifRVuIIUay/EjErdtzp+w9JZMqUnbqh1ztptnM85wuvobWNEhSF05D78VK3tJxfRmuL/y/KhKzTXsEPefet7qzybx1LD21YFHZ22X+DUoqdOzf8MKUEPMQ5ndRIkLp66K12fE0jUHi63DGI2El8K2YpatwmX5nNaiNtxRhPfsGQH+JDWmvhhVTV5f3eo8ETI8iGCninKXErg+2UW5oweZSs0U7uJcC3Zbb6DAi+eVr6ZwvzId+3xKk4uGRwPJErituhpOLIg+KFtAQcr7tUKE8EMDKzx0HB8mg4n8/5QrXUvNGw0cMHQam8iVJH2eSO5LaRtvZcTgmRqUe3zxFLFDUx/vKc17xqGAdjLY5m5j5neAG+Ngv3Sb+L8aZd092DjO41fEutWGYcGUtVs/PeDg0BUpIV/Y9K6P/nbdOud83sLOudY60KJywswje95q9rgmmp8b9oRu6bjHAcmUDwzJP3pzqghU22/DSLB1P7bXjvLTsCSv+2/G8Jwlq0Q37xsnRkGFofi97/qeTkZzt1y3qKg5S2wKpZ/EAXdyYGgWQDWA28=
