language: node_js
servers: mongodb
node_js:
- node
- '12'
install:
- cd backend ; npm install
- cd backend ; npm install -dev
script:
- cd backend ; npm test
notifications:
  slack: nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt
env:
  global:
  - secure: gP0fiDII0yBJc1h/g5QfOc07dnWxNDmNmXXq+BF2Ob7SBxRlro6V21ny8dAgRyUMLGchn67Y28zW/fk7QccCWJZNqdiOXgkX1OkknB1QJSmdAX2OLZDnz2beZJ4Ij0bOVoLnurLDj1Qdy3d4SdKTJhdSimKaqP89/wolhnfQSY8ZeNfJ1cGjACk0ihfh/e5YQmX4U7RX5ttAQn8aGeUxdMreZOslHorNvi/fdJ6n2LsYoK0fSYxmrS+oFStTCXy0m6d4s0SFSRYTOuyjvnM5x2HIQSoEk9h+3FeX+/zeNPYtVHI066tr8xqowLcD87/WNCpU63G8xn2HSGTbG1dKtfx4AdNrimNEkka/ap87XQXwb2V/bYFCY3H3zCeLADx0DN0lbcQn/efGIInAtRT32O8xcZgBGELCrd6zbkX00lKtKVXAwjFy43M55pXO6pGeUEbrKE2fk2UOSNliMqczxUx6vdZ8tTSt/+Y8C5y/3p6eLxGqn9hPHMPgchD5zX+xOdAyY2hNiYPC6dO0skkNJTtPwmqvN8062THguPGeZLL76BS/B1yd06Ux0bIJIe8dWgPluNc1MK8Vg8Q34CCx5zVeLHgYKIAuEJPzXBz4DcpyWSXmrDh26g03mqsd9qimSKV7GSpJERq+R7L5MAdzK0FLbSuYCDxsVC6C/U25ysk=
  - secure: fPbYYy2QaMJUGEJxwZkSQ58+3kJwin04KOEqeVNBo1dtyvvPOaBvD1LgKjUgmP8CJZJ3dq92HcA0eXSHYYZQnSyDsxG1bpP8Hwo3lM5xCbNqNQm0hRtmLBT3/EKa/RoLJo1xhUBknw5Ual+orirSnBK18wAdWCmmDG/N+OunfeFMk0dO7XDOmsCIBdJdkKAZLTVeZ97jqdxE0Z/ANfTd4Fh+K/Zsw1oJBdJjk8RhVfYxyEcxk5mfzgKqrLnC3KJpQu7h8lMBF/S+8+rg3Zcra52bPEDEd/22ZJw1Zehflj8CWEdoy6LnKeHPPowY0UpfqCmE0m7OPYosvn1EiWtMhsqq8kvOXJ4hko8ZDjojBzG+kDTHU+IfWSqgXK+IYf7capa9cNBdhp3QsilCCO7vjW2q8cbZztO+zVidxCOXyRgPfQx5TdlY7IWjty11KX+7KYT/2bOjZD3htbV+OJNBMeHjK+yaKOmn9sdgOdt/hiuXUyUap13LjBzFW3tx3NXCWPpKOziGu2V7LDg31a2MTT6qnABHpWqMuvVv5y3QGvoaK4L4FovBiUu16wYFTLWjAs5YtO2oSK1Mlot+KkNY4J7itK1LnpzZ3zn9A1WK9fH1xTWJnjdU7AivesyU38OBrgqZXv8MG/Pqsb07YYIpMDBXvCQ1u5wXCUY7OmYFIGw=
