language: node_js
servers: mongodb
node_js:
- '12'
install:
- cd backend ; npm install
- cd backend ; npm install -dev
script:
- cd backend ; npm test
notifications:
  slack: nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt
env:
  global:
  - secure: Z51h+1iY6DNmMuRvAkWwP154z2eJjl6uXytQck54qZflkVJa1eHs+T+Y4cM5iBNgw62YjJX/N+RQO5D+YQ77QCcI5XkRuWSfft2COlk7h3uMMyoJofvmM/GcrNFH6kMj7kPWScuLrO8RqD+Rf+KfZ/IcjLb7RMh8Afd/Z0mnpsZd+HPQEG3Z8i/xeLiMtpjV1QCgZuSdSmBMZGYjkj69pvrhBfiEMNT1UijjHoQCJ8hCAWYlEicMVLvWsLsG4njQVRb0IqboHKgzwSvEM3qJycZ3rK2/QwIa7BIW8MZzxuV8AN5bhZF8uw9TdgE1Lqdzu53mLqKXk9vZnvMZxAR3I4Fbci2OE4k8G/NgMKjUbJji6RMaNfcaEU8Yc/L9EbMc0lj+P3gSYJF7jr7hJQfCqoJk2tkCFXEP7h9H/Je7hOln1dGrAelC8QdDTGxZmZPdcOwnrkS0IsL8UihOECipvY60Eh+ZCUzFgXD+fV5RhtbHWNhawM8j3PeGtNeDXYvNIIfAKXZcXDAJiMFJ+v3AytLJcIOpsm9Ajn6HvX+S01suaqCKvPag9Rm6A4k6c2iNdrvRCmL4xo2SPcd3UQBRMZpjbulCkVskfvURbtunswIOEhkGrpUzvjzz6STGf80m7h/c+UhN7hwDZSt7QoywDxZrwu1jKdCX8RrZz1SkTC4=
  - secure: uc4GUz3qNDu4N7tkkkOsWQx9ynQaYZ/p0+WXulD2sLEN1cnuZCJMRVj70ISNTlXI2tiTgfK3eJIcZ+KGZt6A15Zo98QWMDfdbzR0xtA4iz7+FTZlmQ5YipCBz0bcqfNhAH8wVVTg8yU0R6hRaFyyGaqwuVvk6xUuHM8tCNUukCJi1Pw0fRdESVX0AgB7XFbPZJzHCWN39yvQnaPtIAbke8/hZWVzdz8i6vd0Melj4pPgzbIJa6Aj/uukefU9tYvix/nsusWTzPiDaAcW+u7wZBzNY/IKNG3/ZxomwQbfFf5puByjAo7ptLeArxKQ2to4x8b+l91ZOQiu2iWLJUqLMypwpWK+ZH/ZhnbmrgBbm5a6CkIbvSeqsUIU6SCT0uNZgZXKDg2HV2aqGDnhgrQwuq3wRnhi2fx7rBS5PQ/zjCzhUwktvV3KzhnFaiGXD8ZUWFRnE3KPNWqd6PVLAou4dWqoSTDuhLLFSXqqWyz4/uQcv5K626qPEfuu4s1AM1bg6Ngc66YsYTZAKqy/fBYGZDlFHdrInDk2BZ2kOo4gzX4cf5h5eW03enI3LVF0MhQdpkVfMa3pdP2cjx1UmVJBA/yMdYoRWlUDXQZUsR/u9oQ3n59yTOzCwnCdBkc6ERyUuOdmZFUaXsYlZBYtGPfOfr5KjrZbGo0Z8FuHcu0FqnM=
