language: node_js
node_js:
- node
- '12'
install:
- cd backend ; npm install
- cd backend ; npm install -dev
script:
- cd backend ; npm test
notifications:
  slack: nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt
env:
  secure: D6IG0fY5UGLTMhAvPjVmcEJoPPdsNZOk5crI1FEc6r9SLGXJHDulWrdk+lC9lSA32bfSpltWABLUiy+wl6VJvc5r0AVNw4mPx5YgVMOdFpvlk8n4EbdshptV/1M91wC9pKMt4NBh0e0dj/MoGplPzr7gGgWcgHZDu4kqC/70rxA/ZDl96zgt8AmkS6s6iPuI/pqByB/BjqbkS5RKeQq03y2f/elbYkHDKX96GYimbPL5H4I3LAnYBmyk4+CTBQhPJnne3eqCt4ex1juF6NupXqR6etpsq0s4nZkL+5Ynh6EQc7s9txvv8Brj/4evfSV2OmN87FSB9hmsQDCnSI2FM5EbtZ02/L+azJTRu2AA78f0OZmBIXli6S7CDvEkZ+TRSgKJFVVM9TnKUof/CCSzMeFXQrHNs5ypfO34GNQUfzPo1u8T7oD2WnAeEK7TUjgxnunZj2dLHOpRd8PUtLsaI4eo96B5RjrVMZksSTPenrVK5438SLV9wpw0Lx82jlfcR9S5w0d6i3rxqK3GfxkbQlO42L3+4yngFbS4x67rSdpf85GDN5RHMPGMcqA5M9SX6M7NkEXWSikVlt/Z13wDi3O2XbMB+19Y1bSjy8LawzNWPVY/K/J2Zay01JJVRtEC3H4rdSnazVjCTGpx5IOJjRFk8Lxu+ts+qVI7lYfVd6Y=
