language: node_js
node_js:
- node
- '12'
install:
- cd backend ; npm install
- cd backend ; npm install -dev
script:
- cd backend ; npm test
notifications:
  slack: nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt
env:
  secure: iLfm4TFzmqbobvYoaV3y/mShnCk0uoR+f4zLXkV2KYMszgIV3GZ8pRpqtUkfK+g2gpaNJ3d0QQBHoYPafKCvHIPIIe5m/XSZhYyjM79QQ7TE8EPr6WK5rshfhQOc7lBuuyIBA+qe7kKLV86knRPr7LG+2NrXJor1LikUCrboX6VSrCdMViL9Z7nBeUSjYx2SkJRD//1kDxGZruVV/7cFN1Rb56bNiF2MMT5By3qYkCv/SQ+rXVj9tomUF3i4AAAqaIziBIGZFhXs+B6kn1guPXqe9HDY9HzyOCo5llUu5KGNXNgdgOlwqISXcXVaO1tjEZxhYaKsMCtL3QyOfBWjigqXGnRBPJayWECNsgn3WGPI5ZNaXiW4zcf2K5ZS4OtTh9/W4VXizn+PTomUYzu52YjNFrCMUQ1rogu28CCj5zqScqrbkYsdRbIqPCHxIzxgNxKIicnBcSsb6OuvbReSioJPL4nsrUBgLkxZbwr+FAugcw0IWqIUyF7TgnzIOJNgWiFYpOkHP7iUUeVOzNp1o236+wRxO+ykYmWMEM7DuYi4t6CH2RGoMyizvB43m2dVQCtz62tJxpxf1aakWoJkwZK5ekY81hllvJzMWFyBVxPSvJzzedVx2muBqjTqyGND8rv0UrYKJWUOtsjm5BHEbUpxAKi8UzyrOAF3cEU5XQ0=
