language: node_js
services: mongodb
node_js:
  - "node"
  - "12"
install:
  - cd backend ; npm install
  - cd backend ; npm install -dev
script:
  - ATLAS_URI=mongodb+srv://SkipperLin:12345678abc@cluster0-zslvh.gcp.mongodb.net/DB?retryWrites=true&w=majority
  - secretOrKey=secret
  - Testing_URI=mongodb+srv://SkipperLin:12345678abc@cluster0-zslvh.gcp.mongodb.net/test?retryWrites=true&w=majority
  - cd backend ; npm test
notifications:
  slack: nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt