language: node_js
node_js:
- node
- '12'
install:
- cd backend ; npm install
- cd backend ; npm install -dev
script:
- cd backend ; npm test
notifications:
  slack: nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt
env:
<<<<<<< HEAD
  matrix:
    secure: p2YmFOQzlap3GegA9eZ0rE8eibTXj+4q7oxUS4LvRYsc9IBky3PjDnUDjyXh9Rn1CiXX39+8XiOX7SljsiW5ICeE+4qxbGv5+S0+vTho8e7N8lp7r5eoyK0h+OZlYoXJLwY+sv3jeeTyoak4DczolbCcI9I3A/n/8k8UIdPL/caIfjqNr7WU+Az4pTnHhwRFukEJAhev0lhPtSz4brjHiPVwR3SzPcbgGT7hBFo9TVI3vQc8mCZUqgtZyVopCmoF3vq1FRiU6TrqffzUPVqYVgHMc0zgY0gytjw3P8gAINcFNcjmV8na9ejtj1KAGll/jd4yHDLeB/XYcXxHN44BBY9f+l4LZvOHNMFSe18eTSX2iiklF+ymcYp0ulEtXCd2rSxY1mCXn6bt4TgytjV2cZfJ7xr6g2HDHZmG6vi0svIUYORRri4lODz3Y4S6otSQi32HTmJZq631XQopkU/q/CmXSQeegsX8ODo/3Y2YdA6uDZfQBI19nXQ2zusjE/xcqD3kysl1gFgzbw3EZ4aRvdUQCDalPk2z6RV94D8m4Vb+WyvxrNe7hQkuorrewO2CCRi77udeyMFSpl6aBjLHuOqwpFWVkw/YHrRRWcgMkw4Suvh4vmWNHHXXs0Z02Tg4dZT1REAXbMI7ZX4PtN9QRE2LQ4lQwihrwyxuWbF5Wm0=
=======
  secure: BlCMToqvlZkbH0t/YEAIFY+qLn7ITmztiQjqnUBdLYM3vR+/GQ+wkYt9u36gqtGjWFNasZJwb5blUKX8CGt/POnEeH4iakZ9U6eOEsDd7Var+zHwsGYcKaGhAS7ZvKGHUqwX1BnSAMJOEz14ZdzIZHSL0k0dp3TGkmIPHy7B0Zu/+3zRwHIV3oyYcHZaerlPg/D1lN9F81KWIS4Lwd/hlCxbPmQ3wAoPsmk6K5oZ7ab/IUjYG+qtBbMjVjLYCYRoGj9toLBbuRGeiPw9bvApH/5MGRfY7ij2JnQ4YzoaZshPcaOqHIoGr4HbR/bV7QZ1XliV3tNEgFZes5e2kyTm4cfUMyQqSoB/cdh0xhB39rcYQw3pvQdHm6SJT9zl3td6n/3bf/MkcblOiQB0ItIX/UfkXs4CA6/QQcM8DmnM4nhl+SKOek+iK18K9vTfrQSoCZDlAgy9nkPsTFwb4QukcqAsg9N8PEPQEOAzX8onHz3KTd/q4pEl+ULLgZ4g3v75C81fTQv1eouZKF6wjQWBEvYPGXOuX/G4Wbi1HaJHWuqIRAMyCnBlAs1gKH6FLiXGnWgAme7GX0tbN+tJkh3KblnwEac8bYz0dBCIcSAtrRKL9xVh9+ckc490whiLT1ryzMyQZehTWcOmRi8ReVUXJoZdjU9RHdV7/rCeLtA85Wo=
>>>>>>> 1aa96c5be1ab5e2c60055d07679be942fdf5b790
