language: node_js
node_js:
- node
- '12'
install:
- cd backend ; npm install
- cd backend ; npm install -dev
script:
- cd backend ; npm test
notifications:
  slack: nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt
env:
  secure: BlCMToqvlZkbH0t/YEAIFY+qLn7ITmztiQjqnUBdLYM3vR+/GQ+wkYt9u36gqtGjWFNasZJwb5blUKX8CGt/POnEeH4iakZ9U6eOEsDd7Var+zHwsGYcKaGhAS7ZvKGHUqwX1BnSAMJOEz14ZdzIZHSL0k0dp3TGkmIPHy7B0Zu/+3zRwHIV3oyYcHZaerlPg/D1lN9F81KWIS4Lwd/hlCxbPmQ3wAoPsmk6K5oZ7ab/IUjYG+qtBbMjVjLYCYRoGj9toLBbuRGeiPw9bvApH/5MGRfY7ij2JnQ4YzoaZshPcaOqHIoGr4HbR/bV7QZ1XliV3tNEgFZes5e2kyTm4cfUMyQqSoB/cdh0xhB39rcYQw3pvQdHm6SJT9zl3td6n/3bf/MkcblOiQB0ItIX/UfkXs4CA6/QQcM8DmnM4nhl+SKOek+iK18K9vTfrQSoCZDlAgy9nkPsTFwb4QukcqAsg9N8PEPQEOAzX8onHz3KTd/q4pEl+ULLgZ4g3v75C81fTQv1eouZKF6wjQWBEvYPGXOuX/G4Wbi1HaJHWuqIRAMyCnBlAs1gKH6FLiXGnWgAme7GX0tbN+tJkh3KblnwEac8bYz0dBCIcSAtrRKL9xVh9+ckc490whiLT1ryzMyQZehTWcOmRi8ReVUXJoZdjU9RHdV7/rCeLtA85Wo=
