language: node_js
servers: mongodb
node_js:
- node
- '12'
install:
- cd backend ; npm install
- cd backend ; npm install -dev
script:
- cd backend ; npm test
notifications:
  slack: nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt
env:
  secure: bfpfGK29N71+d0S/m24CDMpST9tzQG/Zw2RJy/AzSmp+OcOxBjJZmOTQAOr5qGbZ7dpawjgJoZ+eK9cJcXc1JSNtnxGZNW5RUcQin0yY11DDJOLT+SEqA2BqCE/kogM406o1njU3GvVA8gyUp97hN2jK23NH1lpFMzpk5prN9XrlVBG8eL2y9ijNTrNer4cr/o7/TKam3MeKqUdYAvyvD5i2GChdsc2bbfrz0eodfCAoW2L/5ml26T0hDWL0zVgV4zotSvYjIu7GvcEe3TI3ZfNbxSiv7iyIpR+jzkjxYIghXJtG6IqngbNvvlTYOLYu3kBrDmRV/7WCV4nVEWcgtsenigziN67ycyE2PtOHlQoHj/qQ2zIKDtD52qSExXIs4PQvTCVcLaNbeuoRxeGF7mIZ3ihQR2ku/PB808rOqHYyF7Zs3VAlDYNk/ErjDxf41JfgVyRXQKAorhKF7ryYRy823tbjVuPaFSZTdfQ1WOocIAHDJDpvpWZzaaG7W1+LSpr5E7nvzAiuHpQixk44CdkDbQK4mN+jx92G8dw/G8CWfe/UsxpxDioH7URi5V1i3W8yA3taULUus25NAxehXJkdguMtc1kPTp5yoJRObGyHT2aTume3CXU0zB+JQnaB2od3AAXwzkueif8o/ZwHQ2pfd+mU/s3lyG4WQxH4CgM=
