language: node_js
servers: mongodb
node_js:
- node
- '12'
install:
- cd backend ; npm install
- cd backend ; npm install -dev
script:
- cd backend ; npm test
notifications:
  slack: nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt
env:
  global:
    secure: JGX9ppkUduJ1pbpIW27vLA0Zjj3W4HFZWg5bSwyEhaOu+9fvsJREVsRFx/dePqZ3RhXmElg68eQasiilM6aYLjwJwRTOc6IqahCjdBHZPOdTa4GjFP3VJaea8l7yM1MZySvEKPQWri/WQ4PBvlKwhpCsMgKQ4qbSUsPktqJ0Pjia8uREi1T15e3rjEX1LSnLicSmBgpwbQX21S3pSgO3zKYL1Zx3TZhhyKgb1KdOUFvJa/pH7+1W9hDnagJSjg25jTe81Q863wJwnJAXLrCu8XWPjgC23rv7cnIRJqiFmq5RDGM9IUHBqk9XT2PlctOHNxHgwc7/nHhyRwmxE9prqcnIyEi//jA9jiJ5qKQssMFdqBNIGWFuaUOixyAHzg/eDtEDEE9uLBnCZDC9DwV26zml6DNGCyMIlUqEsnGbM4924zE61vjTK/IJX9JhC9Dq1x89EyDDyi9rEGfQnndpa9PgrjEiLXctUUAsKCUeRa0W/24oxeyRG/kb/AwePWocEez8J5wpaFFY91n/y3lR5ZELDIRbyVtBD3sz9t0XRwAaeNX5oGBxNQDsI1yuIc4+cLp4jwNz34ngPwaAiWjC937RZmywX3KxVSOoZE73zTbb95Lt63MX9gX53WPTmA06a1IEo9KunLGNrmxWtixFlSVg8jrWqkCwQTiud2k+21o=
