language: node_js
node_js:
- node
- '12'
install:
- cd backend ; npm install
- cd backend ; npm install -dev
script:
- cd backend ; npm test
notifications:
  slack: nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt
env:
  matrix:
    secure: p2YmFOQzlap3GegA9eZ0rE8eibTXj+4q7oxUS4LvRYsc9IBky3PjDnUDjyXh9Rn1CiXX39+8XiOX7SljsiW5ICeE+4qxbGv5+S0+vTho8e7N8lp7r5eoyK0h+OZlYoXJLwY+sv3jeeTyoak4DczolbCcI9I3A/n/8k8UIdPL/caIfjqNr7WU+Az4pTnHhwRFukEJAhev0lhPtSz4brjHiPVwR3SzPcbgGT7hBFo9TVI3vQc8mCZUqgtZyVopCmoF3vq1FRiU6TrqffzUPVqYVgHMc0zgY0gytjw3P8gAINcFNcjmV8na9ejtj1KAGll/jd4yHDLeB/XYcXxHN44BBY9f+l4LZvOHNMFSe18eTSX2iiklF+ymcYp0ulEtXCd2rSxY1mCXn6bt4TgytjV2cZfJ7xr6g2HDHZmG6vi0svIUYORRri4lODz3Y4S6otSQi32HTmJZq631XQopkU/q/CmXSQeegsX8ODo/3Y2YdA6uDZfQBI19nXQ2zusjE/xcqD3kysl1gFgzbw3EZ4aRvdUQCDalPk2z6RV94D8m4Vb+WyvxrNe7hQkuorrewO2CCRi77udeyMFSpl6aBjLHuOqwpFWVkw/YHrRRWcgMkw4Suvh4vmWNHHXXs0Z02Tg4dZT1REAXbMI7ZX4PtN9QRE2LQ4lQwihrwyxuWbF5Wm0=
