language: node_js
node_js:
- node
- '12'
install:
- cd backend ; npm install
- cd backend ; npm install -dev
script:
- cd backend ; npm test
notifications:
  slack: nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt
env:
  secure: BlCMToqvlZkbH0t/YEAIFY+qLn7ITmztiQjqnUBdLYM3vR+/GQ+wkYt9u36gqtGjWFNasZJwb5blUKX8CGt/POnEeH4iakZ9U6eOEsDd7Var+zHwsGYcKaGhAS7ZvKGHUqwX1BnSAMJOEz14ZdzIZHSL0k0dp3TGkmIPHy7B0Zu/+3zRwHIV3oyYcHZaerlPg/D1lN9F81KWIS4Lwd/hlCxbPmQ3wAoPsmk6K5oZ7ab/IUjYG+qtBbMjVjLYCYRoGj9toLBbuRGeiPw9bvApH/5MGRfY7ij2JnQ4YzoaZshPcaOqHIoGr4HbR/bV7QZ1XliV3tNEgFZes5e2kyTm4cfUMyQqSoB/cdh0xhB39rcYQw3pvQdHm6SJT9zl3td6n/3bf/MkcblOiQB0ItIX/UfkXs4CA6/QQcM8DmnM4nhl+SKOek+iK18K9vTfrQSoCZDlAgy9nkPsTFwb4QukcqAsg9N8PEPQEOAzX8onHz3KTd/q4pEl+ULLgZ4g3v75C81fTQv1eouZKF6wjQWBEvYPGXOuX/G4Wbi1HaJHWuqIRAMyCnBlAs1gKH6FLiXGnWgAme7GX0tbN+tJkh3KblnwEac8bYz0dBCIcSAtrRKL9xVh9+ckc490whiLT1ryzMyQZehTWcOmRi8ReVUXJoZdjU9RHdV7/rCeLtA85Wo=
  matrix:
    secure: Ypkvdb58AlY+uCvnmaa+Kr9KWecYhJLEgFIRkidZhxS0df82OjPxM20LX4PXI0xLEmM/m3iuRIgTjLWOtgH/iMstlscLwNAk59aG6HUT6FEPnjWN0gn/GOX3T2vFffX14LFmIoFDh9ZrFThbG0BEQkKBIWrOm4iPA5tRs4APKphtpE9Um907exyxg29GPrxBV61aMEsRl/mPFCDQPi1xqQflZlV68s2JHPge55JBJaf6a6Ma9Hc1uyRSsSVd8WzX+pqX1hQ1uDu78YOvyexqX4p2EVdc1vfzSe4+ZOHKkECpy9/nRDt3mEQDdTNQ0Egr6haowy8ejA6SPfShtLNXeQ2qWIjsRLFbBQvkELIJmHN9geLur1mFYy4xFWe+hMkcwHh1nDJzeXVPF/urFxXF0NYihLtP1oYTRFkWjQBQEpwfdc71tVmz3AOK1BKkKFkPPppnGlf6RjDUL2gMHw8Ai7s/016750Bns90//DX8vINQDNw5RBjstWaHZLoJZ8ECc0lR0W+QTbYAv5legXykRRgzYY3XI0eJSjXzzI4LcAKLSbpCLofIHirCkpeIv/WGzth6T38arX60BhVLrHGZYLBXSxCKCcD+IJtGs5N2DweQSuwhGQq5qLwoIe3niwOk1kyXU46ixK+bT94mZcE+anwt6kiLfZDi35sqcBEzy7c=
