language: node_js
servers: mongodb
node_js:
- node
- '12'
install:
- cd backend ; npm install
- cd backend ; npm install -dev
script:
- cd backend ; npm test
notifications:
  slack: nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt
env:
  global:
  - secure: MlBjxcifubsmGg2jK0UaYD2yqrv6UnKNZ0rF9113116vXhcgrJYxB1qwPUy9WTwHqPxnawR/jBJ2PN+Biy8txR3PJOVGF8hWFp11/J9LMGpERVa79NkNYgf7kr4hHRCtsPkxTImGkdyfQVM5rtTdU6Av82q4Il8c2BVs4DnumOze6dRiXJJnCaqods+4guiHP8IUyG4GgJzd3AnA0iv7b7fHtyiQfxbpinf7c/KrL6FWsLpxa3QkPi5N9Sy4bTOVbw+ZuwR6wMqp0Z6tfgKIxc7iAAmtk7LYK4rPai/TtUwkvDaiwiRo/oRHvsjUBL4zsBgi4aLukJkB9MkKEXIIIgfEiVTlA0xcTrkYoLJBuikSppI3xrSQt1c4MvvDgLhWIT3WaKigQPOvGbx9pvujTAL52s9YpoGGXnsTS8XcOW2zhLB4xorNuQi9eFsAfSLQjuLuA4A/gMNQDqeYbfRbg/urpyEWYFxkAFbGAnL9sHrNFgJSMRrr6Hg5xFUq0Bt7MryxlIvBJlVifZypWyWXCD1ln6yNxnuXYubi2l6OJuYRMpGm8xmbfxP8HzAkb+SQ80MSbzllPGGnkun1++nobqNyCijk4hGFryujCxhRIqzoL8jxAzetGC6s71tC5gHCf/47z+q9PuBEMH91l6LVmovFjFiAUH+k5pSZHscQISw=
  - secure: XvedNOaCaT8jM+IyIAmwouuqqI+rkq84h8tWm4gmIo2tnwpjf74ESodOIAQfWElGY0IpLivhCSggg7xjutryezyH3Zm75QTpHShzdIM1TipS1NRDsuqpiLbXpcZq7r3i9DWhRnP/CsLxX0/7yhkssq0e2rrly5zoe2KyYVrQ6ZORF+JRfI4SdJkdyxSalbQ5d5u2qWvi2gTB2AG3Qjp0FYYVA9R3gI5ZSjfBHAtGQk6i4Yymbxr5pV5QFgChGlOAES4FjmTz8Zo8SDjHXswo2/Hn9CEMcO/nm1N3kdvyXtILvx1bnbYD32nC4wN8GqxnnI3eQbwrzZXmElb+iQ0tW9VI0W2P8bkMEbi2gJui7oQcpHbLTMVekQGfa7rrRZ3ppyG045UljDg6tIjZVw9g9EQ5eYUme3EnXVwKdWEYd39uO6rXJoR2Su/WlX8CV9IGMxId24vMvc6OPxFf5HzFqUiZsii9UmdR1yIaonHhTCV2zyAwmRp6m7DSJO5MWdqZzvsP1iV9jcFHUmoIpK/79L8+5lcsQCYjoE2bWbkDy95OrSvUgDSGhTeSbW50NdToCB+wH7MlvE6l67GfQp1u8OolPaffT1haPy+lR02k5IZoMC+JMTsv/dJD/lgPfnbi1KNp2fivN+d2v/e3VoveuEHYnvHe0Dwil9rPolYDEcg=
